### ISSUE TITLE
Querying entities breaks when no entities have a component

### ISSUE THREAD

**Issue by cschram** [jzhu98/star-entity#9]
When querying the EntityManager for entities that have a particular component before any entity has been created with that component an assertion fails:

>core.exception.AssertError@../../../.dub/packages/star-entity-1.0.7/source/star/entity/entity.d(924): Assertion failure

It's essential that this does not fail, but rather returns an empty list; for instance, in cases where a MovementSystem runs before any entities have actually been created.

A possible solution would be to check `EntityManager.hasType()` on every component supplied to `EntityManager.entities()` before doing anything else, and returning an empty list if `hasType` returns false.

**Comment by jzhu98** [comment]
Merged.
